version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: thinking_styles
      POSTGRES_USER: thinkingassesment
      POSTGRES_PASSWORD: ninja
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U thinkingassesment"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
