services:
  - type: web
    name: thinking-styles-backend
    env: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: thinking-styles-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://thinking-styles1.vercel.app
  
  - type: pserv
    name: thinking-styles-db
    env: postgres
    region: oregon
    plan: free
    databaseName: thinking_styles
    databaseUser: postgres
